import type { Metadata } from "next";
import { Roboto, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ClientThemeProvider from "./ClientThemeProvider/ClientThemeProvider";
import "react-responsive-carousel/lib/styles/carousel.min.css";


const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <ClientThemeProvider font={roboto}>{children}</ClientThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
